import {TupacCamel,
    SnoopDawgBlack,
    EminemWhite,
    EminemLavendar,
    DoodleLavender,
    BobMarleyWhite,
    BobMarleyLavender,
    BobMarleyCamel,
    BeegieBlack,
    Bear,
    SnoopDawgBlackFront,
    SnoopDawgBlackBack,
    EminemWhiteBack,
    EminemWhiteFront,
    EminemLavendarFront,
    EminemLavendarBack,
    BobMarleyWhiteFront,
    BobMarleyWhiteBack,
    BobMarleyLavenderFront,
    BobMarleyLavenderBack,
    BobMarleyCamelBack,
    BobMarleyCamelFront,
    BeegieBlackBack,
    BeegieBlackFront,
    DoodleLavenderBack,
    DoodleLavenderFront,
} from "./images/Photos"

export const Products=[
    {   
        Id:1,
        Title:"Eminem",
        Colors:['White',"#B2A4D4"],
        Images:[EminemWhiteFront,EminemWhiteBack,EminemLavendarFront,EminemLavendarBack],
        Price:600,
        Image:EminemLavendar
       
    },
    {   Id:2,
        Title:"Tu Pac",
        Colors:['#BF9972'],
        Images:[TupacCamel],
        Price:600,
        Image:TupacCamel,
    },
    {   Id:3,
        Title:"Beegie",
        Colors:['Black'],
        Images:[BeegieBlackFront,BeegieBlackBack],
        Price:600,
        Image:BeegieBlack,
        
    },
    {   Id:4,
        Title:"Doodle",
        Colors:["#B2A4D4"],
        Images:[DoodleLavender],
        Price:600,
        Image:DoodleLavender
    },
    {   Id:5,
        Title:"Eminem",
        Colors:['White',"#B2A4D4","#B2A4D4"],
        Images:[EminemWhiteFront,EminemWhiteBack,EminemLavendarFront,EminemLavendarBack],
        Price:600,
        Image:EminemWhite
    },
    {   Id:6,
        Title:"Snoop Dawg",
        Colors:['Black'],
        Images:SnoopDawgBlackFront,
        Price:600,
        Image:SnoopDawgBlack
    },
    {   Id:7,
        Title:"Bob Marley",
        Colors:["#BF9972","#B2A4D4",'White'],
        Images:[BobMarleyWhiteFront,BobMarleyWhiteBack,BobMarleyLavenderFront,BobMarleyLavenderBack,BobMarleyCamelFront,BobMarleyCamelBack],
        Price:600,
        Image:BobMarleyWhite
    },
    {   Id:8,
        Title:"Bob Marley",
        Colors:["#BF9972","#B2A4D4",'White'],
        Images:[BobMarleyWhiteFront,BobMarleyWhiteBack,BobMarleyLavenderFront,BobMarleyLavenderBack,BobMarleyCamelFront,BobMarleyCamelBack],
        Price:600,
        Image:BobMarleyCamel
    },
    {   Id:9,
        Title:"Bob Marley",
        Colors:["#BF9972","#B2A4D4",'White'],
        Images:[BobMarleyWhiteFront,BobMarleyWhiteBack,BobMarleyLavenderFront,BobMarleyLavenderBack,BobMarleyCamelFront,BobMarleyCamelBack],
        Price:600,
        Image:BobMarleyLavender
    },
    {   Id:10,
        Title:"Bear",
        Colors:['White','Black'],
        Images:[Bear],
        Image:Bear,
        Price:450,
    },
    
    
]
export const RecentProducts=[
    
    
    {   Id:3,
        Title:"Beegie",
        Colors:["Black"],
        Images:{Black:BeegieBlack},
        Price:600,
        Image:BeegieBlack,
        
    },
    {   Id:7,
        Title:"Snoop Dawg",
        Colors:['Black'],
        Images:{Black:SnoopDawgBlack},
        Price:600,
        Image:SnoopDawgBlack
    },
    {   Id:5,
        Title:"Eminem",
        Colors:['White',"#B2A4D4"],
        Images:{White:EminemWhite,Lavender:EminemLavendar},
        Price:600,
        Image:EminemWhite
    },
    
    
]